# Site settings
title: 风中清焰
url: "http://laobubu.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing  this blog.
  improve yourself 1% every single day,you will be 38 times better one year later!

# Your information
email: rodyyyy@qq.com
author: rody
avatar: "avatar.jpg"
profile: 不知者无畏
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "rodyyyy@qq.com"
  GitHub: "https://rodyyyy.github.io/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://www.zhibo8.cc/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
